[package]
name = "sha2_v08_wrapper"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = { version = "0.8.2", default-features = false }

[features]
default = ["std"]
std = [ "sha2/std" ]
